[tool.poetry]
name = "driveoff"
version = "0.1.0"
description = "Prototype for research drive offboarding and archiving, from IDS team."
authors = ["Chris Seal <c.seal@auckland.ac.nz>", "Noel Zeng", "Libby Li", "James Love", "Andrew Wilson"]
readme = "README.md"
packages = [
	{ include = "cli"},
	{ include = "api" }
]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
