// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * CodeResponse
 *
 * Project code.
 */
export type CodeResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Code
     */
    code: string;
};

/**
 * CreateSubmissionRequest
 *
 * Request body for creating an archive submission.
 */
export type CreateSubmissionRequest = {
    /**
     * Drive Name
     */
    drive_name: string;
    /**
     * Retention Period Years
     */
    retention_period_years: number;
    /**
     * Retention Period Justification
     */
    retention_period_justification?: string | null;
    data_classification?: DataClassification;
    /**
     * Project Id
     */
    project_id?: number | null;
};

/**
 * CreateSubmissionResponse
 *
 * Response returned after creating an archive submission.
 */
export type CreateSubmissionResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * DataClassification
 *
 * Data classification labels defined in Research
 * Data Management Policy.
 */
export type DataClassification = 'Public' | 'Internal' | 'Sensitive' | 'Restricted';

/**
 * DriveInfoResponse
 *
 * Combined drive + project info returned by the driveinfo endpoint.
 */
export type DriveInfoResponse = {
    drive: DriveResponse;
    project: ProjectResponse;
};

/**
 * DriveResponse
 *
 * Research drive storage info.
 */
export type DriveResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Allocated Gb
     */
    allocated_gb: number;
    /**
     * Used Gb
     */
    used_gb: number;
    /**
     * Free Gb
     */
    free_gb: number;
    /**
     * Percentage Used
     */
    percentage_used: number;
    /**
     * Date
     */
    date: string;
    /**
     * First Day
     */
    first_day?: string | null;
    /**
     * Last Day
     */
    last_day?: string | null;
};

/**
 * ErrorResponse
 *
 * Error response returned by the API.
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MemberResponse
 *
 * Project member with role.
 */
export type MemberResponse = {
    role: RoleResponse;
    person: PersonResponse;
};

/**
 * PersonResponse
 *
 * Person summary for display.
 */
export type PersonResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Username
     */
    username?: string | null;
};

/**
 * ProjectResponse
 *
 * Project summary for display.
 */
export type ProjectResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Division
     */
    division: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Codes
     */
    codes?: Array<CodeResponse>;
    /**
     * Members
     */
    members?: Array<MemberResponse>;
};

/**
 * RoleResponse
 *
 * Project role.
 */
export type RoleResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * SubmissionResponse
 *
 * Archive submission record returned by the submission endpoint.
 */
export type SubmissionResponse = {
    /**
     * Drive Id
     */
    drive_id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Drive Name
     */
    drive_name: string;
    /**
     * Retention Period Years
     */
    retention_period_years: number;
    /**
     * Retention Period Justification
     */
    retention_period_justification: string | null;
    data_classification: DataClassification;
    /**
     * Archive Date
     */
    archive_date: string;
    /**
     * Archive Location
     */
    archive_location: string;
    /**
     * Is Completed
     */
    is_completed: boolean;
    /**
     * Created Timestamp
     */
    created_timestamp: string;
    /**
     * Manifest
     */
    manifest: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetDriveInfoApiV1DriveinfoGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Drive Name
         */
        drive_name: string;
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/driveinfo';
};

export type GetDriveInfoApiV1DriveinfoGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDriveInfoApiV1DriveinfoGetError = GetDriveInfoApiV1DriveinfoGetErrors[keyof GetDriveInfoApiV1DriveinfoGetErrors];

export type GetDriveInfoApiV1DriveinfoGetResponses = {
    /**
     * Successful Response
     */
    200: DriveInfoResponse;
};

export type GetDriveInfoApiV1DriveinfoGetResponse = GetDriveInfoApiV1DriveinfoGetResponses[keyof GetDriveInfoApiV1DriveinfoGetResponses];

export type GetSubmissionApiV1SubmissionGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Drive Name
         */
        drive_name: string;
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/submission';
};

export type GetSubmissionApiV1SubmissionGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubmissionApiV1SubmissionGetError = GetSubmissionApiV1SubmissionGetErrors[keyof GetSubmissionApiV1SubmissionGetErrors];

export type GetSubmissionApiV1SubmissionGetResponses = {
    /**
     * Successful Response
     */
    200: SubmissionResponse;
};

export type GetSubmissionApiV1SubmissionGetResponse = GetSubmissionApiV1SubmissionGetResponses[keyof GetSubmissionApiV1SubmissionGetResponses];

export type CreateSubmissionApiV1SubmissionPostData = {
    body: CreateSubmissionRequest;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/submission';
};

export type CreateSubmissionApiV1SubmissionPostErrors = {
    /**
     * Drive already archived
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSubmissionApiV1SubmissionPostError = CreateSubmissionApiV1SubmissionPostErrors[keyof CreateSubmissionApiV1SubmissionPostErrors];

export type CreateSubmissionApiV1SubmissionPostResponses = {
    /**
     * Successful Response
     */
    201: CreateSubmissionResponse;
};

export type CreateSubmissionApiV1SubmissionPostResponse = CreateSubmissionApiV1SubmissionPostResponses[keyof CreateSubmissionApiV1SubmissionPostResponses];
