// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ArchiveJobStage
 *
 * Lifecycle stages for an archive job.
 *
 * State transitions:
 * queued -> packaging -> uploading -> writing_manifest -> cleanup -> completed
 * any non-terminal stage -> failed  (on unhandled exception)
 * any non-terminal stage -> abandoned  (on API restart mid-job)
 */
export type ArchiveJobStage = 'queued' | 'packaging' | 'writing_manifest' | 'uploading' | 'cleanup' | 'completed' | 'failed' | 'abandoned';

/**
 * CodeResponse
 *
 * Project code.
 */
export type CodeResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Code
     */
    code: string;
};

/**
 * CreateRetrievalRequest
 *
 * Request body for starting an archive retrieval job.
 */
export type CreateRetrievalRequest = {
    /**
     * Destination Path
     */
    destination_path: string;
};

/**
 * CreateRetrievalResponse
 *
 * Response returned after scheduling an archive retrieval job.
 */
export type CreateRetrievalResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * CreateSubmissionRequest
 *
 * Request body for creating an archive submission.
 */
export type CreateSubmissionRequest = {
    /**
     * Drive Name
     */
    drive_name: string;
    /**
     * Retention Period Years
     */
    retention_period_years: number;
    /**
     * Retention Period Justification
     */
    retention_period_justification?: string | null;
    data_classification?: DataClassification;
    /**
     * Project Id
     */
    project_id?: number | null;
    /**
     * Force
     */
    force?: boolean;
};

/**
 * CreateSubmissionResponse
 *
 * Response returned after creating an archive submission.
 */
export type CreateSubmissionResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * DataClassification
 *
 * Data classification labels defined in Research
 * Data Management Policy.
 */
export type DataClassification = 'Public' | 'Internal' | 'Sensitive' | 'Restricted';

/**
 * DriveInfoResponse
 *
 * Combined drive + project info returned by the driveinfo endpoint.
 */
export type DriveInfoResponse = {
    drive: DriveResponse;
    project: ProjectResponse;
};

/**
 * DriveResponse
 *
 * Research drive storage info.
 */
export type DriveResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Allocated Gb
     */
    allocated_gb: number;
    /**
     * Used Gb
     */
    used_gb: number;
    /**
     * Free Gb
     */
    free_gb: number;
    /**
     * Percentage Used
     */
    percentage_used: number;
    /**
     * Date
     */
    date: string;
    /**
     * First Day
     */
    first_day?: string | null;
    /**
     * Last Day
     */
    last_day?: string | null;
};

/**
 * ErrorResponse
 *
 * Error response returned by the API.
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MemberResponse
 *
 * Project member with role.
 */
export type MemberResponse = {
    role: RoleResponse;
    person: PersonResponse;
};

/**
 * PatchRetrievalRequest
 *
 * Request body for partially updating an archive retrieval record.
 *
 * Only fields present in the request body are applied; omitted fields are
 * left unchanged.  Timestamps (last_updated, completed, failed) are managed
 * server-side based on the resulting stage value.
 */
export type PatchRetrievalRequest = {
    stage?: RetrievalJobStage | null;
    /**
     * Failure Reason
     */
    failure_reason?: string | null;
    /**
     * Retrieved Part Keys Json
     */
    retrieved_part_keys_json?: string | null;
};

/**
 * PatchSubmissionRequest
 *
 * Request body for partially updating an archive submission record.
 *
 * Only fields present in the request body are applied; omitted fields are
 * left unchanged. Timestamps (last_updated, completed) are managed
 * server-side based on the resulting stage value.
 */
export type PatchSubmissionRequest = {
    stage?: ArchiveJobStage | null;
    /**
     * Failure Reason
     */
    failure_reason?: string | null;
    /**
     * Cleanup Succeeded
     */
    cleanup_succeeded?: boolean | null;
    /**
     * Cleanup Error
     */
    cleanup_error?: string | null;
    /**
     * Archive File Key
     */
    archive_file_key?: string | null;
    /**
     * Archive Object Prefix
     */
    archive_object_prefix?: string | null;
    /**
     * Archive Manifest Key
     */
    archive_manifest_key?: string | null;
    /**
     * Archive Part Keys Json
     */
    archive_part_keys_json?: string | null;
    /**
     * Archive Part Count
     */
    archive_part_count?: number | null;
    /**
     * Archive Total Bytes
     */
    archive_total_bytes?: number | null;
};

/**
 * PersonResponse
 *
 * Person summary for display.
 */
export type PersonResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Username
     */
    username?: string | null;
};

/**
 * ProjectResponse
 *
 * Project summary for display.
 */
export type ProjectResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Division
     */
    division: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Codes
     */
    codes?: Array<CodeResponse>;
    /**
     * Members
     */
    members?: Array<MemberResponse>;
};

/**
 * RetrievalJobStage
 *
 * Lifecycle stages for an archive retrieval job.
 *
 * State transitions:
 * queued -> restoring -> downloading -> extracting -> completed
 * any non-terminal stage -> failed  (on unhandled exception)
 */
export type RetrievalJobStage = 'queued' | 'restoring' | 'downloading' | 'extracting' | 'completed' | 'failed';

/**
 * RetrievalResponse
 *
 * Archive retrieval record returned by the retrieval endpoint.
 */
export type RetrievalResponse = {
    /**
     * Id
     */
    id: number | null;
    /**
     * Drive Name
     */
    drive_name: string;
    /**
     * Submission Id
     */
    submission_id: number;
    /**
     * Destination Path
     */
    destination_path: string;
    stage: RetrievalJobStage;
    /**
     * Failure Reason
     */
    failure_reason: string | null;
    /**
     * Started Timestamp
     */
    started_timestamp: string | null;
    /**
     * Last Updated Timestamp
     */
    last_updated_timestamp: string | null;
    /**
     * Completed Timestamp
     */
    completed_timestamp: string | null;
    /**
     * Failed Timestamp
     */
    failed_timestamp: string | null;
};

/**
 * RoleResponse
 *
 * Project role.
 */
export type RoleResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Name
     */
    name: string;
};

/**
 * SubmissionResponse
 *
 * Archive submission record returned by the submission endpoint.
 */
export type SubmissionResponse = {
    /**
     * Drive Id
     */
    drive_id: number;
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Drive Name
     */
    drive_name: string;
    /**
     * Retention Period Years
     */
    retention_period_years: number;
    /**
     * Retention Period Justification
     */
    retention_period_justification: string | null;
    data_classification: DataClassification;
    stage: ArchiveJobStage;
    /**
     * Failure Reason
     */
    failure_reason: string | null;
    /**
     * Failed Timestamp
     */
    failed_timestamp: string | null;
    /**
     * Started Timestamp
     */
    started_timestamp: string | null;
    /**
     * Last Updated Timestamp
     */
    last_updated_timestamp: string | null;
    /**
     * Completed Timestamp
     */
    completed_timestamp: string | null;
    /**
     * Retry Count
     */
    retry_count: number;
    /**
     * Cleanup Succeeded
     */
    cleanup_succeeded: boolean | null;
    /**
     * Cleanup Error
     */
    cleanup_error: string | null;
    /**
     * Archive File Key
     */
    archive_file_key: string | null;
    /**
     * Archive Object Prefix
     */
    archive_object_prefix: string | null;
    /**
     * Archive Manifest Key
     */
    archive_manifest_key: string | null;
    /**
     * Archive Part Keys Json
     */
    archive_part_keys_json: string | null;
    /**
     * Archive Part Count
     */
    archive_part_count: number | null;
    /**
     * Archive Total Bytes
     */
    archive_total_bytes: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetDriveInfoApiV1DriveinfoGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Drive Name
         */
        drive_name: string;
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/driveinfo';
};

export type GetDriveInfoApiV1DriveinfoGetErrors = {
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * Drive or project not found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetDriveInfoApiV1DriveinfoGetError = GetDriveInfoApiV1DriveinfoGetErrors[keyof GetDriveInfoApiV1DriveinfoGetErrors];

export type GetDriveInfoApiV1DriveinfoGetResponses = {
    /**
     * Successful Response
     */
    200: DriveInfoResponse;
};

export type GetDriveInfoApiV1DriveinfoGetResponse = GetDriveInfoApiV1DriveinfoGetResponses[keyof GetDriveInfoApiV1DriveinfoGetResponses];

export type GetSubmissionApiV1SubmissionGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Drive Name
         */
        drive_name: string;
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/submission';
};

export type GetSubmissionApiV1SubmissionGetErrors = {
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * No archive submission found for drive
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSubmissionApiV1SubmissionGetError = GetSubmissionApiV1SubmissionGetErrors[keyof GetSubmissionApiV1SubmissionGetErrors];

export type GetSubmissionApiV1SubmissionGetResponses = {
    /**
     * Successful Response
     */
    200: SubmissionResponse;
};

export type GetSubmissionApiV1SubmissionGetResponse = GetSubmissionApiV1SubmissionGetResponses[keyof GetSubmissionApiV1SubmissionGetResponses];

export type CreateSubmissionApiV1SubmissionPostData = {
    body: CreateSubmissionRequest;
    path?: never;
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/submission';
};

export type CreateSubmissionApiV1SubmissionPostErrors = {
    /**
     * Invalid submission request
     */
    400: ErrorResponse;
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * Drive or project not found
     */
    404: ErrorResponse;
    /**
     * Drive has already been archived
     */
    409: ErrorResponse;
    /**
     * Validation error
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: ErrorResponse;
    /**
     * ProjectDB upstream request failed
     */
    502: ErrorResponse;
};

export type CreateSubmissionApiV1SubmissionPostError = CreateSubmissionApiV1SubmissionPostErrors[keyof CreateSubmissionApiV1SubmissionPostErrors];

export type CreateSubmissionApiV1SubmissionPostResponses = {
    /**
     * Successful Response
     */
    201: CreateSubmissionResponse;
};

export type CreateSubmissionApiV1SubmissionPostResponse = CreateSubmissionApiV1SubmissionPostResponses[keyof CreateSubmissionApiV1SubmissionPostResponses];

export type RetrySubmissionApiV1SubmissionDriveNameRetryPostData = {
    body?: never;
    path: {
        /**
         * Drive Name
         */
        drive_name: string;
    };
    query?: {
        /**
         * Force
         */
        force?: boolean;
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/submission/{drive_name}/retry';
};

export type RetrySubmissionApiV1SubmissionDriveNameRetryPostErrors = {
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * No submission found for drive
     */
    404: ErrorResponse;
    /**
     * Job is active or already completed
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type RetrySubmissionApiV1SubmissionDriveNameRetryPostError = RetrySubmissionApiV1SubmissionDriveNameRetryPostErrors[keyof RetrySubmissionApiV1SubmissionDriveNameRetryPostErrors];

export type RetrySubmissionApiV1SubmissionDriveNameRetryPostResponses = {
    /**
     * Successful Response
     */
    200: CreateSubmissionResponse;
};

export type RetrySubmissionApiV1SubmissionDriveNameRetryPostResponse = RetrySubmissionApiV1SubmissionDriveNameRetryPostResponses[keyof RetrySubmissionApiV1SubmissionDriveNameRetryPostResponses];

export type PatchSubmissionApiV1SubmissionDriveNamePatchData = {
    body: PatchSubmissionRequest;
    path?: never;
    query: {
        /**
         * Submission Id
         */
        submission_id: number;
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/submission/{drive_name}';
};

export type PatchSubmissionApiV1SubmissionDriveNamePatchErrors = {
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * No archive submission found for drive
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchSubmissionApiV1SubmissionDriveNamePatchError = PatchSubmissionApiV1SubmissionDriveNamePatchErrors[keyof PatchSubmissionApiV1SubmissionDriveNamePatchErrors];

export type PatchSubmissionApiV1SubmissionDriveNamePatchResponses = {
    /**
     * Successful Response
     */
    200: SubmissionResponse;
};

export type PatchSubmissionApiV1SubmissionDriveNamePatchResponse = PatchSubmissionApiV1SubmissionDriveNamePatchResponses[keyof PatchSubmissionApiV1SubmissionDriveNamePatchResponses];

export type GetRetrievalApiV1RetrievalDriveNameGetData = {
    body?: never;
    path: {
        /**
         * Drive Name
         */
        drive_name: string;
    };
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/retrieval/{drive_name}';
};

export type GetRetrievalApiV1RetrievalDriveNameGetErrors = {
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * No archive retrieval job found for drive
     */
    404: ErrorResponse;
    /**
     * Validation error
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type GetRetrievalApiV1RetrievalDriveNameGetError = GetRetrievalApiV1RetrievalDriveNameGetErrors[keyof GetRetrievalApiV1RetrievalDriveNameGetErrors];

export type GetRetrievalApiV1RetrievalDriveNameGetResponses = {
    /**
     * Successful Response
     */
    200: RetrievalResponse;
};

export type GetRetrievalApiV1RetrievalDriveNameGetResponse = GetRetrievalApiV1RetrievalDriveNameGetResponses[keyof GetRetrievalApiV1RetrievalDriveNameGetResponses];

export type CreateRetrievalApiV1RetrievalDriveNamePostData = {
    body: CreateRetrievalRequest;
    path: {
        /**
         * Drive Name
         */
        drive_name: string;
    };
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/retrieval/{drive_name}';
};

export type CreateRetrievalApiV1RetrievalDriveNamePostErrors = {
    /**
     * Invalid retrieval request
     */
    400: ErrorResponse;
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * No completed archive submission found for drive
     */
    404: ErrorResponse;
    /**
     * A retrieval job for this drive is already active
     */
    409: ErrorResponse;
    /**
     * Validation error
     */
    422: unknown;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type CreateRetrievalApiV1RetrievalDriveNamePostError = CreateRetrievalApiV1RetrievalDriveNamePostErrors[keyof CreateRetrievalApiV1RetrievalDriveNamePostErrors];

export type CreateRetrievalApiV1RetrievalDriveNamePostResponses = {
    /**
     * Successful Response
     */
    201: CreateRetrievalResponse;
};

export type CreateRetrievalApiV1RetrievalDriveNamePostResponse = CreateRetrievalApiV1RetrievalDriveNamePostResponses[keyof CreateRetrievalApiV1RetrievalDriveNamePostResponses];

export type PatchRetrievalApiV1RetrievalRetrievalIdPatchData = {
    body: PatchRetrievalRequest;
    path: {
        /**
         * Retrieval Id
         */
        retrieval_id: number;
    };
    query?: {
        /**
         * Path
         */
        path?: string;
    };
    url: '/api/v1/retrieval/{retrieval_id}';
};

export type PatchRetrievalApiV1RetrievalRetrievalIdPatchErrors = {
    /**
     * Invalid or missing API key
     */
    401: ErrorResponse;
    /**
     * Retrieval job not found
     */
    404: ErrorResponse;
    /**
     * Validation error
     */
    422: unknown;
};

export type PatchRetrievalApiV1RetrievalRetrievalIdPatchError = PatchRetrievalApiV1RetrievalRetrievalIdPatchErrors[keyof PatchRetrievalApiV1RetrievalRetrievalIdPatchErrors];

export type PatchRetrievalApiV1RetrievalRetrievalIdPatchResponses = {
    /**
     * Successful Response
     */
    200: RetrievalResponse;
};

export type PatchRetrievalApiV1RetrievalRetrievalIdPatchResponse = PatchRetrievalApiV1RetrievalRetrievalIdPatchResponses[keyof PatchRetrievalApiV1RetrievalRetrievalIdPatchResponses];
